-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGc1XfH370cgLDsPf
Gos/Fjmr9G/uP9fxNCrrG0iMtK6gCgYIKoZIzj0DAQehRANCAARY4RPOaGpF3AuD
LUZaURbZuZF4Bj/p7x4y+6cGNfAaDCw2SBPk/WkX642IwbQ//4oTLoPMLmhOxR2d
qdaoctcc
-----END PRIVATE KEY-----